import { useRef } from 'react';
import { T } from '../../theme/theme.js';
import Bt from '../ui/Bt.jsx';
import QRSvg from './QRSvg.jsx';
import { qrSerialData } from './qrHelpers.js';

function QRDetailView({qrData,label,sub,serials,kitId,onClose}){
  const qrRef = useRef(null);
  return(<div style={{display:"flex",flexDirection:"column",alignItems:"center",gap:16}}>
    <div ref={qrRef}><QRSvg data={qrData} size={200} padding={3}/></div>
    <div style={{textAlign:"center"}}>
      <div style={{fontSize:16,fontWeight:700,color:T.tx,fontFamily:T.u}}>{label}</div>
      {sub&&<div style={{fontSize:10,color:T.mu,fontFamily:T.m,marginTop:2}}>{sub}</div>}</div>
    <div style={{padding:10,borderRadius:8,background:"rgba(255,255,255,.03)",border:"1px solid "+T.bd,width:"100%"}}>
      <div style={{fontSize:9,color:T.dm,fontFamily:T.m,wordBreak:"break-all",textAlign:"center"}}>{qrData}</div></div>
    {serials&&serials.length>0&&<div style={{width:"100%"}}>
      <div style={{fontSize:10,textTransform:"uppercase",letterSpacing:1.2,color:T.am,fontFamily:T.m,marginBottom:8}}>
        Serialized Component QR Codes</div>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>
        {serials.map(s=><div key={s.key} style={{display:"flex",flexDirection:"column",alignItems:"center",gap:4,
          padding:10,borderRadius:8,background:"rgba(251,191,36,.02)",border:"1px solid rgba(251,191,36,.1)"}}>
          <QRSvg data={qrSerialData(kitId,s.key,s.serial)} size={80} padding={3}/>
          <div style={{fontSize:9,fontWeight:600,color:T.tx,fontFamily:T.m,textAlign:"center"}}>{s.label}</div>
          <div style={{fontSize:8,color:T.am,fontFamily:T.m}}>{s.serial}</div></div>)}</div></div>}
    <div style={{display:"flex",gap:8}}>
      <Bt v="primary" onClick={()=>{const svgEl=qrRef.current?.querySelector('svg');
        const svgHtml=svgEl?svgEl.outerHTML:'<div style="width:200px;height:200px;display:flex;align-items:center;justify-content:center;color:#999">QR unavailable</div>';
        const w=window.open('','_blank','width=360,height=500');
        w.document.write('<!DOCTYPE html><html><head><title>Print QR - '+label+'</title>'+
        '<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;600;700&family=Outfit:wght@400;600;700&display=swap" rel="stylesheet">'+
        '<style>body{display:flex;flex-direction:column;align-items:center;padding:32px;font-family:"Outfit",sans-serif;color:#111;background:#fff}'+
        '.qr-label{font-size:16px;font-weight:700;margin-top:16px;text-align:center}'+
        '.qr-data{font-family:"IBM Plex Mono",monospace;font-size:9px;color:#7a7a9a;margin-top:8px;word-break:break-all;text-align:center;max-width:280px}'+
        '.qr-footer{margin-top:16px;font-size:8px;color:#aaa;font-family:"IBM Plex Mono",monospace}'+
        '@media print{body{padding:40px}}</style></head><body>');
        w.document.write(svgHtml);
        w.document.write('<div class="qr-label">'+label+'</div>');
        if(sub)w.document.write('<div style="font-size:11px;color:#666;margin-top:4px;text-align:center">'+sub+'</div>');
        w.document.write('<div class="qr-data">'+qrData+'</div>');
        w.document.write('<div class="qr-footer">Generated by COCO Gear</div>');
        w.document.write('<script>window.onload=function(){window.print()}<\/script></body></html>');w.document.close()}}>Print</Bt>
      <Bt onClick={onClose}>Close</Bt></div></div>);}

export default QRDetailView;
