import { T } from '../../theme/theme.js';
import Bt from '../ui/Bt.jsx';
import QRSvg from './QRSvg.jsx';

function QRPrintSheet({items,onClose}){
  return(<div>
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}>
      <div style={{fontSize:12,color:T.mu,fontFamily:T.m}}>{items.length} QR codes</div>
      <div style={{display:"flex",gap:8}}>
        <Bt v="primary" onClick={()=>window.print()}>Print</Bt>
        <Bt onClick={onClose}>Close</Bt></div></div>
    <style>{`@media print{body *{visibility:hidden !important}
      #qr-print-sheet,#qr-print-sheet *{visibility:visible !important}
      #qr-print-sheet{position:fixed;top:0;left:0;width:100%;background:#fff !important;padding:16px 20px;z-index:99999}
      *{-webkit-print-color-adjust:exact;print-color-adjust:exact;color-adjust:exact}}`}</style>
    <div id="qr-print-sheet" style={{background:"#fff",color:"#111"}}>
      <div style={{textAlign:"center",marginBottom:12,paddingBottom:8,borderBottom:"2px solid #2563eb"}}>
        <div style={{fontSize:9,fontWeight:700,color:"#2563eb",fontFamily:"'IBM Plex Mono',monospace",textTransform:"uppercase",letterSpacing:3,marginBottom:4}}>QR Code Sheet</div>
        <div style={{fontSize:10,color:"#7a7a9a",fontFamily:"'IBM Plex Mono',monospace"}}>{items.length} codes | Generated {new Date().toLocaleDateString("en-US",{month:"long",day:"numeric",year:"numeric"})}</div>
      </div>
      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(160px,1fr))",gap:12,padding:4}}>
      {items.map(item=><div key={item.id} style={{display:"flex",flexDirection:"column",alignItems:"center",gap:6,
        padding:12,border:"1px solid #d4d4de",borderRadius:6,background:"#fff",pageBreakInside:"avoid"}}>
        <QRSvg data={item.qrData} size={120}/>
        <div style={{fontSize:11,fontWeight:700,color:"#0f0f23",fontFamily:"'Outfit',sans-serif",textAlign:"center"}}>{item.label}</div>
        <div style={{fontSize:8,color:"#7a7a9a",fontFamily:"'IBM Plex Mono',monospace",textAlign:"center",wordBreak:"break-all"}}>{item.sub}</div></div>)}</div>
      <div style={{marginTop:12,fontSize:8,color:"#7a7a9a",fontFamily:"'IBM Plex Mono',monospace",textAlign:"center",borderTop:"1px solid #d4d4de",paddingTop:6}}>Generated by COCO Gear</div>
    </div></div>);}

export default QRPrintSheet;
